#:kivy 2.0.0
#:include defmapview.kv

MDBottomNavigation:
    MDBottomNavigationItem:
        text: "Map"
        name: "screen1"
        icon: "map"
        BoxLayout:
            DefMapView:
    MDBottomNavigationItem:
        text: "Controls"
        name: "screen2"
        icon: "target"
        BoxLayout:
            Button:
            Button:
            Button:
    MDBottomNavigationItem:
        text: "Status"
        name: "screen3"
        icon: "graph"